### PR TITLE
README: Use Handlebars syntax highlighting

### PR DESCRIPTION
**Pull request by Turbo87**

### CODE REVIEW

**Comment by gmurphey** [comment]
@homu r+

**Comment by gmurphey** [comment]
Thanks!

**Comment by Turbo87** [comment]
@gmurphey looks like the build is somewhat broken, but I don't think my changes are actually responsible for that ;)

**Comment by gmurphey** [comment]
No, definitely not your changes. I'll track this down!

**Comment by gmurphey** [comment]
@homu retry

**Pull request merged**
