### PR TITLE
Update to Ember CLI 2.12.0, move to NPM deps & remove deprecation warnings

### PR DESCRIPTION
**Pull request by willviles**
This PR is somewhat of a spring clean for Ember Masonry Grid. It:

- [x] Updates the addon to `Ember CLI 2.12.0`.
- [x] Sources dependencies from NPM.
- [x] Adds a service for handling Masonry config, and allows imagesLoaded to be conditionally used.
- [x] Fixes deprecation on `didUpdateAttrs` in `Ember CLI >= 2.0.0`.
- [ ] Ensures tests are appropriately updated.
- [ ] Ensures README is updated with information on optional imagesLoaded config.

#### Updates to Ember CLI 2.12.0
The addon has been updated to Ember CLI 2.12.0. ESLint is now the linter of choice - [ember-suave](https://github.com/DockYard/ember-suave) is removed in favour of [eslint-plugin-ember-suave](https://github.com/DockYard/eslint-plugin-ember-suave), and all ESLint errors are satisfied.

#### Bower -> NPM
As per #40, Bower dependencies are removed in favour of sourcing [Masonry](https://github.com/desandro/masonry) and [imagesloaded](https://github.com/desandro/imagesloaded)  from NPM using `broccoli-funnel` and `broccoli-merge-trees`.

#### Conditional use of ImagesLoaded 
As per #53, there is now an option to disable [imagesloaded](https://github.com/desandro/imagesloaded) from being imported to the app `vendor.js`.

#### didUpdateAttrs deprecation
As per #56, Ember CLI >= 2.0.0's deprecation of passing arguments to didUpdateAttrs is fixed by using [ember-diff-attrs](https://github.com/workmanw/ember-diff-attrs) to listen to changes to Masonry options.

#### Dummy app content security
Explicitly adds a `contentSecurityPolicy` to the dummy app to remove warnings about images and inline styles.

### CODE REVIEW

**Comment by sevab** [comment]
@willviles I'm trying to upgrade my app to 2.13+ here. Is this PR functional to use as a fork?

**Comment by willviles** [comment]
@sevab - yep! I'm using the `spring-clean` branch in multiple production apps!

**Comment by sevab** [comment]
@willviles works well, thanks a lot for your work on the fixes!
Will be moving to bricks.js soon, seems a much better alternative and is written in ES6.

**Comment by willviles** [comment]
@gmurphey what's the best way of moving forward with this addon? This PR does a lot of the work to update Ember Masonry Grid and I've been using it in production for 6 months or so.

@sevab I looked at moving to Bricks.js, but unfortunately unlike Masonry, there's no support for responsive containers.

**Pull request closed without merging**
